# Generated by Django 3.2.23 on 2024-04-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.FileField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
